### ISSUE TITLE
currupted zip or corrupted upload ?

### ISSUE THREAD

**Issue by coucou747** [binance-chain/bsc-snapshots#1]
After few downloadings, I have this checksum 1998c48f54a6bf477a068973ae800c8b

and few corrupted files in the zip.

Am I alone with this issue ?

**Comment by davidalbela** [comment]
> After few downloadings, I have this checksum 1998c48f54a6bf477a068973ae800c8b
> 
> and few corrupted files in the zip.
> 
> Am I alone with this issue ?

I had the same issue with `Bsc-20210727.zip` (size 366.0GB) trying to unzip inside the docker container built with [bsc](https://github.com/binance-chain/bsc) Dockerfile (busybox). Unfortunally that container includes a `wget` with the following issue: https://bugs.busybox.net/show_bug.cgi?id=8821

After update the `wget` on the container: 
```
apk add --no-cache unzip
```
I was able to unzip the snapshot.

BTW @wangkai1994 could be possible indicate the hash algorithm of the checksum on `README.md` file, replace the md5sum for a sha1sum or sha256sum, and use `tarball` file instead zip for the snapshot?
