### ISSUE TITLE
download link for Snapshot Bsc-20210804.zip giving 403

### ISSUE THREAD

**Issue by abhishekk049** [binance-chain/bsc-snapshots#11]
@guagualvcha can you please check

**Comment by jingniao** [comment]
403 when wget and browser download

**Comment by iakisme** [comment]
@abhishekk049  @jingniao  let me update.

**Comment by jingniao** [comment]
> @abhishekk049 @jingniao let me update.

thanks reply

**Comment by iakisme** [comment]
@jingniao  @abhishekk049  done
