### ISSUE TITLE
How to clean up the redundant node data

### ISSUE THREAD

**Issue by github-chenzhiqing** [binance-chain/bsc-snapshots#13]
My node data is growing very fast, and now it has almost occupied 1T of hard disk space, but the snapshot downloaded on github is only 500G, how can I clean up the large amount of redundant data? Please advise, thank you!

**Comment by 0fuz** [comment]
Hello. tested on geth-1.1.2:
`sudo ./geth  --config ./config.toml --datadir ./node  --cache 10000 --ws snapshot prune-state`
--cache means how much MB for processes

You can wrap command below with this
`nohup sudo ./geth  --config ./config.toml --datadir ./node  --cache 10000 --ws snapshot prune-state &`
to let geth prune data as job, you dont need keep terminal opened.

For me it takes 6-12hr.
