### ISSUE TITLE
Error when extracting erigon snapshot

### ISSUE THREAD

**Issue by billyadelphia** [binance-chain/bsc-snapshots#170]
any idea why ?
[erigon-20220806.tar.lz4](https://download.bsc-snapshot.workers.dev/snapshot/erigon-20220806.tar.lz4)

```
tar -I lz4 -xvf erigon.tar.lz4
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

```
root@bsc3 ~/downloads # ls -la
total 790362784
drwxr-xr-x  2 root root         4096 Sep  9 09:47 .
drwx------ 10 root root         4096 Sep  9 07:47 ..
-rwxrwxrwx  1 root root 809331052544 Sep  9 09:47 erigon.tar.lz4
```

also tried decompressing it first
```
root@bsc3 ~/downloads # lz4 -d erigon.tar.lz4
Decoding file erigon.tar
Decompressed : 1101464 MB  Error 68 : Unfinished stream

root@bsc3 ~/downloads # tar -xvf erigon.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by amurde** [comment]
Same here.

tar (GNU tar) 1.30
*** LZ4 command line interface 64-bits v1.8.3, by Yann Collet ***

**Comment by antoni7654** [comment]
Same here. I tried both ways with the 20220806 erigon snapshot. Then I thought that maybe it was an aria2c downloader issue, deleted the files and tried again with wget. Could download around 80% of the file but it stopped with Error 500: Internal Server Error and have not been able to download the part of the file I don't have

**Comment by jasonyic** [comment]
same issue here and the file a incomplete. I tried `BNB48CLUB` and it works: https://github.com/BNB48Club/bsc-snapshots

**Comment by wangtsiao** [comment]
same issue here.

**Comment by antoni7654** [comment]
https://github.com/BNB48Club/bsc-snapshots worked for me. The last file, the previous gave me errors at download. They update the file every 36 hours. You better install the newest Erigon version because bsc had a hard fork recently and data format is different, so you need the new node software.
