### ISSUE TITLE
20211002 is incomplete

### ISSUE THREAD

**Issue by gomes7997** [binance-chain/bsc-snapshots#23]
Only 11GB when downloaded. Unzip fails with:

server/data-seed/geth/chaindata/16228103.ldb
server/data-seed/geth/chaindata/16299900.ldb
server/data-seed/geth/chaindata/16233099.ldb
server/data-seed/geth/chaindata/16346472.ldb
server/data-seed/geth/chaindata/16320242.ldb

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by iakisme** [comment]
fixed @gomes7997
