### ISSUE TITLE
Expiration is coming to quickly on EU geth snapshot

### ISSUE THREAD

**Issue by jcaffet** [binance-chain/bsc-snapshots#35]
The snapshot provided through the EU endpoint expired only few hours after release :

```
<Error>
<Code>ExpiredToken</Code>
<Message>The provided token has expired.</Message>
<Token-0>
(...)
</Token-0>
<RequestId>0D65W7BRJANT9XYB</RequestId>
<HostId>x/DEGv+P2cScgsX0J+VC40OtvoO1EA2LC6jqzqm3N5RfuWMaujX4IkhLe2QG+qdnPlaTQMM9Rvc=</HostId>
</Error>

```

**Comment by guagualvcha** [comment]
Thanks for report, Fixing it now

**Comment by iakisme** [comment]
done

**Comment by Nojoix** [comment]
Thank you, but can you tell me why the EU snapshot size is different from Asia one ?

**Comment by nftgeek** [comment]
We need full archive snapshot data in EU as well.  NOT pruned. @iakisme

**Comment by iakisme** [comment]
@Nojoix  Please wait some hours, it will be fixed tmr.

**Comment by iakisme** [comment]
> archive snapshot data

Need discussion and approve from dev team.

**Comment by Lajoix** [comment]
@iakisme 3rd attempt to download and EU snap, it seems corrupt
