### ISSUE TITLE
complement the snapshot instruction

### ISSUE THREAD

**Issue by barryz** [binance-chain/bsc-snapshots#4]
Detailed instruction may help users use the snapshot easily and quickly

**Comment by huangsuyu** [comment]
https://docs.binance.org/smart-chain/developer/snapshot.html

**Comment by shelldor73** [comment]
Hello, but could you please give the exact command to run after downloading  geth and the snapshot please ? it's not that clear in the documentation.
I am using an amazon i3en.2xlarge instance and i had 150k blocks to catch but it's very slow, after now 8hours i i have 115k blocks to catchup...

**Comment by wfucksky** [comment]
> Hello, but could you please give the exact command to run after downloading geth and the snapshot please ? it's not that clear in the documentation.
> I am using an amazon i3en.2xlarge instance and i had 150k blocks to catch but it's very slow, after now 8hours i i have 115k blocks to catchup...

hi , i use aws c5.4xlarge. i also need 3 days to sync

**Comment by huangsuyu** [comment]
> Hello, but could you please give the exact command to run after downloading geth and the snapshot please ? it's not that clear in the documentation.
> I am using an amazon i3en.2xlarge instance and i had 150k blocks to catch but it's very slow, after now 8hours i i have 115k blocks to catchup...

 Please checkout the instructions in README https://github.com/binance-chain/bsc-snapshots/blob/main/README.md
