### ISSUE TITLE
What does verified mean?

### ISSUE THREAD

**Issue by hellodword** [binance-chain/bsc-snapshots#44]
The latest snapshot is marked as "verified", does it mean someone use them to sync successfully on a new machine?

Or may you **test it on a new machine** and provide your system info/hardware details, settings, `config.toml`, start command and more details? @iakisme

**Comment by hellodword** [comment]
3 days go, I really tried a lot, I have some experience of other networks, but I'm still going round in circles on BSC.

**Comment by guagualvcha** [comment]
I have tested with the snapshot, it can work.
