### ISSUE TITLE
How to reduce db size?

### ISSUE THREAD

**Issue by mikhail-khalizev** [binance-chain/bsc-snapshots#54]
Hi.

I started a full sync from scratch, downloaded almost the entire blockchain (except for the last 3 months so far) and the folder is over 2TB in size.

But your snapshot of the full blockchain is less than 1TB.

How is this possible? Do you have any secret how to reduce the size of the database by almost 2 times? Can you share?

**Comment by mikhail-khalizev** [comment]
For sync I use official configuratoin from https://github.com/binance-chain/bsc/releases with setting `SyncMode = "full"`.

**Comment by SnakePin** [comment]
They use the command `geth snapshot prune-state --datadir ./node` which deletes the past states. If it was an archive node's snapshot, all the past states would be available to be queried so the database size would be large.

**Comment by mikhail-khalizev** [comment]
Thanks!
