### ISSUE TITLE
Does this dataset support archive mode?

### ISSUE THREAD

**Issue by netquery** [binance-chain/bsc-snapshots#64]
Does it support `--gcmode archive`?

**Comment by maurodelazeri** [comment]
no, this dateset is a full node

**Comment by masayil** [comment]
> Does it support `--gcmode archive`?

both --syncmode full and  --gcmode archive

**Comment by netquery** [comment]
> no, this dateset is a full node

Thank you! Does full node support `eth_getLogs` interface?

**Comment by allada** [comment]
Archive nodes are extremely large, but I do provide a free one here (requires AWS account to pay for data transfer fees): https://github.com/allada/bsc-archive-snapshot

However, this is not a single node, it is multiple slices of archive nodes that when put together make a full archive node. If you really want to try and put (currently) ~23TB onto one machine, you could combine all the slices together and import them into a single instance... or just use a proxy (like outlined in the readme) to run multiple geth instances and bind them into a single instance from the web3 API perspective.

**Comment by netquery** [comment]
> Archive nodes are extremely large, but I do provide a free one here (requires AWS account to pay for data transfer fees): https://github.com/allada/bsc-archive-snapshot
> 
> However, this is not a single node, it is multiple slices of archive nodes that when put together make a full archive node. If you really want to try and put (currently) ~23TB onto one machine, you could combine all the slices together and import them into a single instance... or just use a proxy (like outlined in the readme) to run multiple geth instances and bind them into a single instance from the web3 API perspective.

Thank you!
