### ISSUE TITLE
The 20211129 snapshot is broken

### ISSUE THREAD

**Issue by Undead8** [binance-chain/bsc-snapshots#70]
The 20211129 snapshot appears to be broken. 

The logs will freeze at `Allocated cache and file handles` and not progress further.

**Comment by gioratofra** [comment]
I also downloaded, and I reach "head state missing, repairing" have patience

**Comment by tpalazzorossi** [comment]
> I also downloaded, and I reach "head state missing, repairing" have patience

Like 5 hours waiting and it doesn't work so yes it's broken

**Comment by Undead8** [comment]
I am now getting this error:

![image](https://user-images.githubusercontent.com/33240024/143945129-cdb1d544-14dc-4e3c-9893-5548bbff6523.png)

**Comment by Undead8** [comment]
@iakisme Last snapshot is broken. Could you update another one very soon? That would be greatly appreciated.

**Comment by gioratofra** [comment]
Mine started to sync after rolling back some blocks

**Comment by Undead8** [comment]
> Mine started to sync after rolling back some blocks

Did you see the same errors as me? I will let it run and see if it manages to repair itself...

**Comment by tpalazzorossi** [comment]
> Mine started to sync after rolling back some blocks

`lvl=info msg="Imported new chain segment"          blocks=1   txs=387 mgas=63.384 elapsed=11m42.425s mgasps=0.090`

Did you get crazy mgasps like this?

**Comment by gioratofra** [comment]
I have "importing heavy sidechain segment" about 500 blocks

**Comment by Undead8** [comment]
Ok seems that the errors above were because I forgot to init the genesis state before starting the sync.

`./geth --datadir node init genesis.json`

I did the above command before replacing the chaindata and triecache folders. I will let it run and see if it start syncing eventually.

**Comment by Undead8** [comment]
@iakisme I have not managed to sync with that snapshot. Could you confirm if it was working on your side and if not, could you upload another one as soon as possible? That would be greatly appreciated.

**Comment by berktaylan** [comment]
after hours of downloading & unzip, really feelsBadMan.

Can someone check ? @iakisme @guagualvcha

**Comment by newb23** [comment]
I am filing an issue, as instructed:

Snapshot: 20211129
Geth: Geth/v1.1.5-8ff7d531/linux-amd64/go1.16.10
Ubuntu - Baremetal

`t=2021-11-29T22:48:07+0000 lvl=eror msg="Snapshot extension registration failed" peer=d014aaf2 err="peer connected on snap without compatible eth support"
t=2021-11-29T22:48:33+0000 lvl=eror msg="Snapshot extension registration failed" peer=32dc271e err="peer connected on snap without compatible eth support"
t=2021-11-29T22:48:53+0000 lvl=eror msg="Snapshot extension registration failed" peer=1125cc47 err="peer connected on snap without compatible eth support"
t=2021-11-29T22:48:56+0000 lvl=eror msg="Snapshot extension registration failed" peer=0f8f49f1 err="peer connected on snap without compatible eth support"
t=2021-11-29T22:49:13+0000 lvl=info msg="Imported new chain segment"             blocks=2   txs=798 mgas=108.751 elapsed=4m45.751s  mgasps=0.381  number=13,036,067 hash=0x7edf88b5ed4a62274805f8a0371919425599e5c97000433f240056d251039c46 age=23h8m58s  dirty="74.41 MiB"
t=2021-11-29T22:49:15+0000 lvl=eror msg="Snapshot extension registration failed" peer=a6c868a1 err="peer connected on snap without compatible eth support"
t=2021-11-29T22:49:16+0000 lvl=eror msg="Snapshot extension registration failed" peer=70fd5af7 err="peer connected on snap without compatible eth support"
t=2021-11-29T22:49:28+0000 lvl=eror msg="Snapshot extension registration failed" peer=bac4b784 err="peer connected on snap without compatible eth support"
t=2021-11-29T22:49:36+0000 lvl=eror msg="Snapshot extension registration failed" peer=01eec99a err="peer connected on snap without compatible eth support"
t=2021-11-29T22:49:50+0000 lvl=eror msg="Snapshot extension registration failed" peer=527b5c7f err="peer connected on snap without compatible eth support"
t=2021-11-29T22:50:29+0000 lvl=eror msg="Snapshot extension registration failed" peer=6ff70d82 err="peer connected on snap without compatible eth support"`

After the error message, the message that followed is the only message I am receiving.

**Comment by GarrixWong** [comment]
same issue here

**Comment by vae520283995** [comment]
The snapshot is indeed broken, I waited for a few hours without any response

**Comment by feifan314** [comment]
INFO [11-30|04:17:48.244] Starting Geth on Ethereum mainnet...
INFO [11-30|04:17:48.247] Maximum peer count                       ETH=2000 LES=0 total=2000
INFO [11-30|04:17:48.247] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [11-30|04:17:48.247] Sanitizing cache to Go's GC limits       provided=100,000 updated=42870
INFO [11-30|04:17:48.248] Set global gas cap                       cap=25,000,000
INFO [11-30|04:17:48.248] Allocated trie memory caches             clean=6.28GiB dirty=10.47GiB
INFO [11-30|04:17:48.248] Allocated cache and file handles         database=/root/server/data-seed/geth/chaindata cache=16.75GiB handles=524,288

**Comment by blackerhot** [comment]
broken too. waiting for 10 hrs of download. thanks

**Comment by blackerhot** [comment]
Why someone see other logs after
 INFO [11-30|04:17:48.248] Allocated cache and file handles database=/root/server/data-seed/geth/chaindata cache=16.75GiB handles=524,288
 some of us stuck on that line forever ?
 This snap file size is around 1TB . Can we have easy hot fix ? better than download another one and maybe facing same issue ?

**Comment by gioratofra** [comment]
I confirm its broken

**Comment by vietthang207** [comment]
> Why someone see other logs after INFO [11-30|04:17:48.248] Allocated cache and file handles database=/root/server/data-seed/geth/chaindata cache=16.75GiB handles=524,288 some of us stuck on that line forever ? This snap file size is around 1TB . Can we have easy hot fix ? better than download another one and maybe facing same issue ?

I second this.

**Comment by berktaylan** [comment]
any update on it ? like are you aware of the problem ? currently re-uploading etc. ?
@iakisme @guagualvcha

**Comment by Marijus** [comment]
broken for me as well. please upload a new one

**Comment by newb23** [comment]
Another place you can look for issues, is in the <directorydir>/geth/chaindata/LOG file. The output seen below is what was happening during it being "frozen", at a sililar message as this: 

> INFO [11-30|04:17:48.248] Allocated cache and file handles database=/root/server/data-seed/geth/chaindata cache=16.75GiB handles=524,288

`=============== Nov 29, 2021 (UTC) ===============
18:43:56.480404 table@recovery recovered @32301305 Gk·7538 Ck·0 Cb·0 S·2124998 Q·31814152780
18:43:56.480689 table@recovery recovering @32301306
18:43:56.487736 table@recovery recovered @32301306 Gk·7463 Ck·0 Cb·0 S·2121421 Q·31814182738
18:43:56.487761 table@recovery recovering @32301309
18:43:56.494961 table@recovery recovered @32301309 Gk·7525 Ck·0 Cb·0 S·2123411 Q·31814164916
18:43:56.494974 table@recovery recovering @32301310
18:43:56.502036 table@recovery recovered @32301310 Gk·7424 Ck·0 Cb·0 S·2124513 Q·31814186194`

**Comment by blackerhot** [comment]
> Another place you can look for issues, is in the /geth/chaindata/LOG file. The output seen below is what was happening during it being "frozen", at a similar message as this:
> 
> > INFO [11-30|04:17:48.248] Allocated cache and file handles database=/root/server/data-seed/geth/chaindata cache=16.75GiB handles=524,288
> 
> `=============== Nov 29, 2021 (UTC) =============== 18:43:56.480404 table@recovery recovered @32301305 Gk·7538 Ck·0 Cb·0 S·2124998 Q·31814152780 18:43:56.480689 table@recovery recovering @32301306 18:43:56.487736 table@recovery recovered @32301306 Gk·7463 Ck·0 Cb·0 S·2121421 Q·31814182738 18:43:56.487761 table@recovery recovering @32301309 18:43:56.494961 table@recovery recovered @32301309 Gk·7525 Ck·0 Cb·0 S·2123411 Q·31814164916 18:43:56.494974 table@recovery recovering @32301310 18:43:56.502036 table@recovery recovered @32301310 Gk·7424 Ck·0 Cb·0 S·2124513 Q·31814186194`
> 
> @blackerhot @vietthang207 @feifan314

yes I was waiting for more 1-2 hrs. but there was others problems as well, same as above reply from others.

**Comment by Undead8** [comment]
I downloaded again and can confirm that it is indeed broken.

![image](https://user-images.githubusercontent.com/33240024/144051765-621dcaca-3b65-4bd4-a250-0ffdd3b5878e.png)

**Comment by Undead8** [comment]
@iakisme Thanks for the upload sir! I'm closing the issue.
