### ISSUE TITLE
Impossible reorg, please file an issue

### ISSUE THREAD

**Issue by newb23** [binance-chain/bsc-snapshots#71]
I am filing an issue, as instructed:

Snapshot: 20211129
Geth: Geth/v1.1.5-8ff7d531/linux-amd64/go1.16.10
Ubuntu - Baremetal

t=2021-11-29T22:48:07+0000 lvl=eror msg="Snapshot extension registration failed" peer=d014aaf2 err="peer connected on snap without compatible eth support" t=2021-11-29T22:48:33+0000 lvl=eror msg="Snapshot extension registration failed" peer=32dc271e err="peer connected on snap without compatible eth support" t=2021-11-29T22:48:53+0000 lvl=eror msg="Snapshot extension registration failed" peer=1125cc47 err="peer connected on snap without compatible eth support" t=2021-11-29T22:48:56+0000 lvl=eror msg="Snapshot extension registration failed" peer=0f8f49f1 err="peer connected on snap without compatible eth support" t=2021-11-29T22:49:13+0000 lvl=info msg="Imported new chain segment" blocks=2 txs=798 mgas=108.751 elapsed=4m45.751s mgasps=0.381 number=13,036,067 hash=0x7edf88b5ed4a62274805f8a0371919425599e5c97000433f240056d251039c46 age=23h8m58s dirty="74.41 MiB" t=2021-11-29T22:49:15+0000 lvl=eror msg="Snapshot extension registration failed" peer=a6c868a1 err="peer connected on snap without compatible eth support" t=2021-11-29T22:49:16+0000 lvl=eror msg="Snapshot extension registration failed" peer=70fd5af7 err="peer connected on snap without compatible eth support" t=2021-11-29T22:49:28+0000 lvl=eror msg="Snapshot extension registration failed" peer=bac4b784 err="peer connected on snap without compatible eth support" t=2021-11-29T22:49:36+0000 lvl=eror msg="Snapshot extension registration failed" peer=01eec99a err="peer connected on snap without compatible eth support" t=2021-11-29T22:49:50+0000 lvl=eror msg="Snapshot extension registration failed" peer=527b5c7f err="peer connected on snap without compatible eth support" t=2021-11-29T22:50:29+0000 lvl=eror msg="Snapshot extension registration failed" peer=6ff70d82 err="peer connected on snap without compatible eth support"

After the error message, the message that followed is the only message I am receiving.

Opened this issue for specific tracking, I also mentioned this in #70

**Comment by iakisme** [comment]
fixed
