### ISSUE TITLE
Current full block number unavailable

### ISSUE THREAD

**Issue by jlinzhou** [binance-chain/bsc-snapshots#73]
After I use the snapshots, error:
t=2021-11-30T06:21:55+0000 lvl=eror msg="Current full block number unavailable" hash=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b

**Comment by Undead8** [comment]
See #70

**Comment by jlinzhou** [comment]
> See #70

Thank you!
