### ISSUE TITLE
Get notification when snapshot being updated

### ISSUE THREAD

**Issue by JohnsonCaii** [binance-chain/bsc-snapshots#74]
Is there any way to get a notification when the snapshot is updated?

I think the only way to catch up with the BSC blockchain is downloading & extracting & using the snapshot data immediately when the new snapshot is provided.

**Comment by algobotishere** [comment]
Subscribe on updates on issues on github

**Comment by ggxed** [comment]
Just write a microservice that will monitor the update and download the snapshot itself after the release
