### ISSUE TITLE
4 days since last snaphot...

### ISSUE THREAD

**Issue by zigg76** [binance-chain/bsc-snapshots#77]
Nodes are almost impossible to sync with a 4 days old snapshot.
Can you please upload a new one ? 
Every 3 days is a good sequence, please keep it up. Thanks !

**Comment by TehnobitSystems** [comment]
Please update shapshot. Dear BSC-guys, you promised to update every 3 days, but why are there no updates?

**Comment by zigg76** [comment]
5 days now :'(

**Comment by zigg76** [comment]
opa opa !
new snap !

**Comment by TehnobitSystems** [comment]
> opa opa !
> new snap !

Why was the previous snapshot 1.3 gigabytes in size, and this one 800 gigabytes?

**Comment by zigg76** [comment]
i think they didn't prune the last one. it was an quick hotfix snapshot 'cos the snapshot ofthe day before (1/12) was broken.

thanks for the new Snapshot !
