### ISSUE TITLE
I am syncing from the snapshot geth-20211208.tar.gz my question is the following

### ISSUE THREAD

**Issue by mycarlos26** [binance-chain/bsc-snapshots#81]
First of all, I am new to the nodes in case the question is not understood.

download the snapshot and start syncing from yesterday at 8 o'clock at night

the geth service shows the following output.

Based on the information displayed, is it normal for me to start downloading everything again? my storage will fill up, which is a nvme ssd samsung 970 evo plus 2tb

**./geth_linux --config ./config.toml --datadir ./mainnet --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=snap --snapshot=false --diffsync**

dic 10 11:05:49 bsc geth[4420]: INFO [12-10|11:05:49.742] Imported new block receipts              count=62   elapsed=838.836ms number=8,345,584  hash=7f5a05..450ff6 age=5mo3w5d   size=10.96MiB
dic 10 11:05:50 bsc geth[4420]: INFO [12-10|11:05:50.462] Imported new block receipts              count=39   elapsed=712.172ms number=8,345,623  hash=aac792..d5478c age=5mo3w5d   size=6.73MiB
dic 10 11:05:51 bsc geth[4420]: INFO [12-10|11:05:51.536] Imported new block receipts              count=113  elapsed=1.030s    number=8,345,736  hash=6e56fc..986b4d age=5mo3w5d   size=17.32MiB
dic 10 11:05:52 bsc geth[4420]: INFO [12-10|11:05:52.262] Imported new block receipts              count=38   elapsed=721.130ms number=8,345,774  hash=5565fc..1a520a age=5mo3w5d   size=6.09MiB
dic 10 11:05:53 bsc geth[4420]: INFO [12-10|11:05:53.088] Imported new block receipts              count=37   elapsed=812.492ms number=8,345,811  hash=8469f5..78049b age=5mo3w5d   size=6.46MiB
dic 10 11:05:54 bsc geth[4420]: INFO [12-10|11:05:54.474] Imported new block receipts              count=169  elapsed=1.368s    number=8,345,980  hash=f42e4e..8c17d9 age=5mo3w5d   size=25.92MiB
dic 10 11:05:55 bsc geth[4420]: INFO [12-10|11:05:55.020] Imported new block receipts              count=50   elapsed=541.267ms number=8,346,030  hash=8fb05a..c68bb0 age=5mo3w5d   size=7.89MiB
dic 10 11:05:55 bsc geth[4420]: INFO [12-10|11:05:55.718] Imported new block receipts              count=48   elapsed=692.930ms number=8,346,078  hash=d9d183..68e15f age=5mo3w5d   size=6.99MiB
dic 10 11:05:56 bsc geth[4420]: INFO [12-10|11:05:56.725] Imported new block receipts              count=116  elapsed=996.792ms number=8,346,194  hash=f939ea..b93fb8 age=5mo3w5d   size=19.18MiB
dic 10 11:05:57 bsc geth[4420]: INFO [12-10|11:05:57.238] Imported new block receipts              count=12   elapsed=503.771ms number=8,346,206  hash=13b108..22e43f age=5mo3w5d   size=2.24MiB
dic 10 11:05:57 bsc geth[4420]: INFO [12-10|11:05:57.809] Imported new block receipts              count=13   elapsed=558.394ms number=8,346,219  hash=61df30..5558b5 age=5mo3w5d   size=2.20MiB

**Comment by iakisme** [comment]
age=5mo3w5d ? i think you used the wrong datadir

**Comment by mycarlos26** [comment]
Thanks for answering I appreciate it very much.
I am using the service as follows.
[Unit]
Description=BSC Go Client
After=syslog.target network.target
            
[Service]
User=root
Group=root
Type=simple
ExecStart=/home/mycar/bsc/geth --config /home/mycar/bsc/config.toml --datadir /home/mycar/bsc/node --cache 100000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --ws --maxpeers 100 --syncmode=snap --snapshot=false --diffsync
KillMode=process
KillSignal=SIGINT
TimeoutStopSec=90
Restart=on-failure
RestartSec=10s
            
[Install]
WantedBy=multi-user.target

 /home/mycar/bsc/node  in this path I uncompress the snapshot data
Can you please tell me what I'm doing wrong I would appreciate your help. Thank you

**Comment by mycarlos26** [comment]
synced in 12 hours, after days of trial and error
